# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('source', models.CharField(max_length=500)),
                ('date_recieved', models.DateField()),
                ('big_photo', models.TextField()),
                ('youtube_source', models.CharField(max_length=1000)),
                ('photo_1', models.CharField(max_length=1000)),
                ('protest_photo', models.CharField(default='http://a.abcnews.com/images/International/EPA_blm_south_africa_01_as_160713_4x3_992.jpg', max_length=1000)),
            ],
        ),
    ]
