# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activist',
            name='quotes',
            field=models.TextField(default='None'),
        ),
    ]
